### PR TITLE
Update icon for windows, linux, macos and android

### PR DESCRIPTION
**Pull request by Thjj**
Icon now in 1:1 aspect ratio
Added icons in smaller resolution

### CODE REVIEW

**Review by rnayabed — CHANGES_REQUESTED** [review]
`macos-icon.icns` and `windows-icon.ico` and all the android icons that were removed are required for the executable installer binaries.

**Comment by Thjj** [comment]
> `macos-icon.icns` and `windows-icon.ico` and all the android icons that were removed are required for the executable installer binaries.

`macos-icon.icns`,`windows-icon.ico` and all Android icons are where they should be. They only have a 1:1 aspect ratio and for windows and macos I added icons in lower resolution.

**Review by rnayabed — APPROVED** [review]
good

**Comment by rnayabed** [comment]
Tested with macos and android. works fine

**Pull request merged**
